default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: Waldo_development

test:
  <<: *default
  database: Waldo_test

production:
  <<: *default
  database: Waldo_production
  username: brian
  password: 